#!/usr/bin/env python3
"""Maintainer utility: flatten Google rules from a local domain-list-community checkout."""
import argparse
from pathlib import Path
import re
import subprocess


def flatten(data):
    visited, entries = set(), set()
    covered_regex = set()
    # These two Play CDN patterns are strict subsets of suffix rules in the same group.
    redundant = {
        r'regexp:^r+[0-9]+(---|\.)sn-(2x3|ni5|j5o)\w{5}\.' + domain.replace('.', r'\.') + '$': domain
        for domain in ['xn--ngstr-lra8j.com', 'googlevideo.com']
    }

    def visit(name):
        if not re.fullmatch(r'[a-z0-9-]+', name):
            raise ValueError('Unsupported include: ' + name)
        if name in visited:
            return
        visited.add(name)
        for number, line in enumerate((data / name).read_text().splitlines(), 1):
            tokens = line.split('#', 1)[0].split()
            if not tokens:
                continue
            value, *attributes = tokens
            if value.startswith('include:'):
                # Include attribute filters have different semantics; never silently broaden them.
                if attributes:
                    raise ValueError(f'Unsupported filtered include: {name}:{number}')
                visit(value.removeprefix('include:'))
                continue
            if any(not attribute.startswith('@') for attribute in attributes):
                raise ValueError(f'Unsupported attributes: {name}:{number}')
            if value in redundant:
                covered_regex.add(redundant[value])
                continue
            exact = value.startswith('full:')
            value = value.removeprefix('full:').removeprefix('domain:').lower()
            if not re.fullmatch(r'[a-z0-9](?:[a-z0-9.-]*[a-z0-9])?', value):
                raise ValueError(f'Unsupported domain rule: {name}:{number}: {value}')
            entries.add(('full:' if exact else '') + value)

    visit('google')
    if covered_regex - entries:
        raise ValueError('A redundant CDN regexp lost its covering suffix rule')
    if not entries:
        raise ValueError('Google domain list is empty')
    return sorted(entries), sorted(visited)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('checkout', type=Path)
    checkout = parser.parse_args().checkout.resolve()
    entries, sources = flatten(checkout / 'data')
    revision = subprocess.check_output(['git', '-C', str(checkout), 'rev-parse', 'HEAD'], text=True).strip()
    license_text = (checkout / 'LICENSE').read_text()
    rules = Path(__file__).resolve().parents[1] / 'rules'
    header = ('# Source: https://github.com/v2fly/domain-list-community\n'
              f'# Revision: {revision}\n'
              '# License: domain-list-community-LICENSE (MIT)\n'
              '# Generated by scripts/import_google_domains.py; includes recursively expanded.\n'
              '# All domain attributes included; full: preserves exact hostname matching.\n'
              '# Included files: ' + ', '.join(sources) + '\n')
    (rules / 'google-domains.txt').write_text(header + '\n'.join(entries) + '\n')
    (rules / 'domain-list-community-LICENSE').write_text(license_text)
    print(f'Imported {len(entries)} Google rules from {len(sources)} source files.')


if __name__ == '__main__':
    main()
